### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Resoluciones** [kumaisu/PremisesEvent#2]
Hi!  Can you explain a little more what this plugin does?  Thank you!!!!!

**Comment by kumaisu** [comment]
Because I am not good at English
· To count the block destruction
· Score scoring on the type of block
· Distribution of special items and support for updates

**Comment by kumaisu** [comment]
This is under development for the purpose of supporting the player's communication event in large-scale grounding

**Comment by Resoluciones** [comment]
Thank you kumaisu for the clarification!

**Comment by kumaisu** [comment]
You are welcome
